<?php
return [
    'kecamatan' => [
        'kec1' => 'Banjarharjo',
        'kec2' => 'Bantarkawung',
        'kec3' => 'Brebes',
        'kec4' => 'Bulakamba',
        'kec5' => 'Bumiayu',
        'kec6' => 'Jatibarang',
        'kec7' => 'Kersana',
        'kec8' => 'Ketanggungan',
        'kec9' => 'Larangan',
        'kec10' => 'Losari',
        'kec11' => 'Paguyangan',
        'kec12' => 'Salem',
        'kec13' => 'Sirampog',
        'kec14' => 'Songgom',
        'kec15' => 'Tanjung',
        'kec16' => 'Tonjong',
        'kec17' => 'Wanasari',
    ],


    'desa' => [
        'kec1' => [
            'Bandungsari',
            'Banjar Lor',
            'Banjarharjo',
            'Blandongan',
            'Ciawi',
            'Cibendung',
            'Cibuniwangi',
            'Cigadung',
            'Cihaur',
            'Cikakak',
            'Cikuya',
            'Cimunding',
            'Cipajang',
            'Dukuhjeruk',
            'Karangmaja',
            'Kertasari',
            'Kubangjero',
            'Malahayu',
            'Parireja',
            'Penanggapan',
            'Pende',
            'Sindangheula',
            'Sukareja',
            'Tegalreja',
            'Tiwulandu',
        ],
        'kec2' => [
            'Bangbayang',
            'Banjarsari',
            'Bantarkawung',
            'Bantarwaru',
            'Cibentang',
            'Cinanas',
            'Ciomas',
            'Jipang',
            'Karangpari',
            'Kebandungan',
            'Legok',
            'Pangebatan',
            'Pengarasan',
            'Sindangwangi',
            'Tambakserang',
            'Telaga',
            'Terlaya',
            'Waru',
        ],
        'kec3' => [
            'Pasar Batang',
            'Brebes',
            'Pulosari',
            'Padasugih',
            'Wangandalem',
            'Gandasuli',
            'Banjaranyar',
            'Kaligangsa Kulon',
            'Kaligangsa Wetan',
            'Limbangan Wetan',
            'Kalimati',
            'Kaliwlingi',
            'Kedunguter',
            'Krasak',
            'Lembarawa',
            'Limbangan Kulon',
            'Pagejugan',
            'Pemaron',
            'Randusanga Kulon',
            'Randusanga Wetan',
            'Sigambir',
            'Tengki',
            'Terlangu',
        ],
        'kec4' => [
            'Bangsri',
            'Banjaratma',
            'Bulakamba',
            'Bulakparen',
            'Bulusari',
            'Cimohong',
            'Cipelem',
            'Dukuhlo',
            'Grinting',
            'Jubang',
            'Karangsari',
            'Kluwut',
            'Luwungragi',
            'Pakijangan',
            'Petunjungan',
            'Pulogading',
            'Rancawuluh',
            'Siwuluh',
            'Tegalglagah',

        ],
        'kec5' => [
            'Adisana',
            'Bumiayu',
            'Dukuhturi',
            'Jatisawit',
            'Kalierang',
            'Kalilangkap',
            'Kalinusu',
            'Kalisumur',
            'Kaliwadas',
            'Langkap',
            'Laren',
            'Negaradaha',
            'Pamijen',
            'Panggarutan',
            'Pruwatan',
        ],
        'kec6' => [
            'Bojong',
            'Buaran',
            'Janegara',
            'Jatibarang Kidul',
            'Jatibarang Lor',
            'Kalialang',
            'Kalipucang',
            'Karanglo',
            'Kebogadung',
            'Kebonagung',
            'Kedungtukang',
            'Kemiriamba',
            'Kendawa',
            'Kertasinduyasa',
            'Klampis',
            'Klikiran',
            'Kramat',
            'Pamengger',
            'Pedeslohor',
            'Rengasbandung',
            'Tegalwulung',
            'Tembelang',

        ],
        'kec7' => [
            'Ciampel',
            'Cigedog',
            'Cikandang',
            'Jagapura',
            'Kemukten',
            'Kersana',
            'Kradenan',
            'Kramatsampang',
            'Kubangpari',
            'Limbangan',
            'Pende',
            'Sindangjaya',
            'Sutamaja',

        ],
        'kec8' => [
            'Baros',
            'Buara',
            'Bulakelor',
            'Ciduwet',
            'Cikeusal Kidul',
            'Cikeusal Lor',
            'Ciseureuh',
            'Dukuh Tengah',
            'Dukuhbadag',
            'Dukuhturi',
            'Jemasih',
            'Karangbandung',
            'Karangmalang',
            'Ketanggungan',
            'Kubangjati',
            'Kubangsari',
            'Kubangwungu',
            'Padakaton',
            'Pamedaran',
            'Sindangjaya',
            'Tanggungsari',
        ],
        'kec9' => [
            'Kamal',
            'Karangbale',
            'Kedungbokor',
            'Larangan',
            'Luwunggede',
            'Pamulihan',
            'Rengaspendawa',
            'Siandong',
            'Sitanggal',
            'Slatri',
            'Wlahar',
        ],
        'kec10' => [
            'Babakan',
            'Blubuk',
            'Bojongsari',
            'Dukuhsalam',
            'Jati Sawit',
            'Kalibuntu',
            'Karangdempel',
            'Karangjunti',
            'Karangsambung',
            'Kecipir',
            'Kedungneng',
            'Limbangan',
            'Losari Kidul',
            'Losari Lor',
            'Negla',
            'Pekauman',
            'Pengabean',
            'Prapag Kidul',
            'Prapag Lor',
            'Radegan',
            'Randusari',
            'Rungkang',
        ],
        'kec11' => [
            'Cilibur',
            'Cipetung',
            'Kedungoleng',
            'Kretek',
            'Pagojengan',
            'Paguyangan',
            'Pakujati',
            'Pandansari',
            'Ragatunjung',
            'Taraban',
            'Wanatirta',
            'Winduaji',
        ],
        'kec12' => [
            'Banjaran',
            'Bentar',
            'Bentarsari',
            'Capar',
            'Ciputih',
            'Citimbang',
            'Gandoang',
            'Ganggawang',
            'Gunung Jaya',
            'Gunung Larang',
            'Gunung Sugih',
            'Gunung Tajem',
            'Indrajaya',
            'Kadumanis',
            'Pabuaran',
            'Pasir Panjang',
            'Salem',
            'Tembongraja',
            'Wanoja',
            'Winduasri',
            'Windusakti',
        ],
        'kec13' => [
            'Batursari',
            'Benda',
            'Buniwah',
            'Dawuhan',
            'Igirklanceng',
            'Kaligiri',
            'Kaliloka',
            'Manggis',
            'Mendala',
            'Mlayang',
            'Plompong',
            'Sridadi',
            'Wanareja',
        ],
        'kec14' => [
            'Cenang',
            'Dukuhmaja',
            'Gegerkunci',
            'Jatimakmur',
            'Jatirokeh',
            'Karangsembung',
            'Songgom',
            'Songgom Lor',
            'Wanacala',
            'Wanatawang',
        ],
        'kec15' => [
            'Karangreja',
            'Kedawung',
            'Kemurang Kulon',
            'Kemurang Wetan',
            'Krakahan',
            'Kubangputat',
            'Lemah Abang',
            'Luwung Gede',
            'Luwungbata',
            'Mundu',
            'Pejagan',
            'Pengaradan',
            'Sarireja',
            'Sengon',
            'Sidakaton',
            'Tanjung',
            'Tegongan',
            'Tengguli',
        ],
        'kec16' => [
            'Galuh Timur',
            'Kalijurang',
            'Karangjongkeng',
            'Kutamendala',
            'Kutayu',
            'Linggapura',
            'Negarayu',
            'Pepedan',
            'Purbayasa',
            'Purwodadi',
            'Rajawetan',
            'Tanggeran',
            'Tonjong',
            'Watujaya',
        ],
        'kec17' => [
            'Pesantunan',
            'Pebatan',
            'Dukuhwringin',
            'Dumeling',
            'Glonggong',
            'Jagalempeni',
            'Keboledan',
            'Kertabesuki',
            'Klampok',
            'Kupu',
            'Lengkong',
            'Sawojajar',
            'Siasem',
            'Sidamulya',
            'Sigentong',
            'Sisalam',
            'Siwungkuk',
            'Tanjungsari',
            'Tegalgandu',
            'Wanasari',
        ],
    ],
];
