<?php
return [

    'Banjarharjo' => [
        'Bandungsari',
        'Banjar Lor',
        'Banjarharjo',
        'Blandongan',
        'Ciawi',
        'Cibendung',
        'Cibuniwangi',
        'Cigadung',
        'Cihaur',
        'Cikakak',
        'Cikuya',
        'Cimunding',
        'Cipajang',
        'Dukuhjeruk',
        'Karangmaja',
        'Kertasari',
        'Kubangjero',
        'Malahayu',
        'Parireja',
        'Penanggapan',
        'Pende',
        'Sindangheula',
        'Sukareja',
        'Tegalreja',
        'Tiwulandu',
    ],
    'Bantarkawung' => [
        'Bangbayang',
        'Banjarsari',
        'Bantarkawung',
        'Bantarwaru',
        'Cibentang',
        'Cinanas',
        'Ciomas',
        'Jipang',
        'Karangpari',
        'Kebandungan',
        'Legok',
        'Pangebatan',
        'Pengarasan',
        'Sindangwangi',
        'Tambakserang',
        'Telaga',
        'Terlaya',
        'Waru',
    ],
    'Brebes' => [
        'Pasar Batang',
        'Brebes',
        'Pulosari',
        'Padasugih',
        'Wangandalem',
        'Gandasuli',
        'Banjaranyar',
        'Kaligangsa Kulon',
        'Kaligangsa Wetan',
        'Limbangan Wetan',
        'Kalimati',
        'Kaliwlingi',
        'Kedunguter',
        'Krasak',
        'Lembarawa',
        'Limbangan Kulon',
        'Pagejugan',
        'Pemaron',
        'Randusanga Kulon',
        'Randusanga Wetan',
        'Sigambir',
        'Tengki',
        'Terlangu',
    ],
    'Bulakamba' => [
        'Bangsri',
        'Banjaratma',
        'Bulakamba',
        'Bulakparen',
        'Bulusari',
        'Cimohong',
        'Cipelem',
        'Dukuhlo',
        'Grinting',
        'Jubang',
        'Karangsari',
        'Kluwut',
        'Luwungragi',
        'Pakijangan',
        'Petunjungan',
        'Pulogading',
        'Rancawuluh',
        'Siwuluh',
        'Tegalglagah',

    ],
    'Bumiayu' => [
        'Adisana',
        'Bumiayu',
        'Dukuhturi',
        'Jatisawit',
        'Kalierang',
        'Kalilangkap',
        'Kalinusu',
        'Kalisumur',
        'Kaliwadas',
        'Langkap',
        'Laren',
        'Negaradaha',
        'Pamijen',
        'Panggarutan',
        'Pruwatan',
    ],
    'Jatibarang' => [
        'Bojong',
        'Buaran',
        'Janegara',
        'Jatibarang Kidul',
        'Jatibarang Lor',
        'Kalialang',
        'Kalipucang',
        'Karanglo',
        'Kebogadung',
        'Kebonagung',
        'Kedungtukang',
        'Kemiriamba',
        'Kendawa',
        'Kertasinduyasa',
        'Klampis',
        'Klikiran',
        'Kramat',
        'Pamengger',
        'Pedeslohor',
        'Rengasbandung',
        'Tegalwulung',
        'Tembelang',

    ],
    'Kersana' => [
        'Ciampel',
        'Cigedog',
        'Cikandang',
        'Jagapura',
        'Kemukten',
        'Kersana',
        'Kradenan',
        'Kramatsampang',
        'Kubangpari',
        'Limbangan',
        'Pende',
        'Sindangjaya',
        'Sutamaja',

    ],
    'Ketanggungan' => [
        'Baros',
        'Buara',
        'Bulakelor',
        'Ciduwet',
        'Cikeusal Kidul',
        'Cikeusal Lor',
        'Ciseureuh',
        'Dukuh Tengah',
        'Dukuhbadag',
        'Dukuhturi',
        'Jemasih',
        'Karangbandung',
        'Karangmalang',
        'Ketanggungan',
        'Kubangjati',
        'Kubangsari',
        'Kubangwungu',
        'Padakaton',
        'Pamedaran',
        'Sindangjaya',
        'Tanggungsari',
    ],
    'Larangan' => [
        'Kamal',
        'Karangbale',
        'Kedungbokor',
        'Larangan',
        'Luwunggede',
        'Pamulihan',
        'Rengaspendawa',
        'Siandong',
        'Sitanggal',
        'Slatri',
        'Wlahar',
    ],
    'Losari' => [
        'Babakan',
        'Blubuk',
        'Bojongsari',
        'Dukuhsalam',
        'Jati Sawit',
        'Kalibuntu',
        'Karangdempel',
        'Karangjunti',
        'Karangsambung',
        'Kecipir',
        'Kedungneng',
        'Limbangan',
        'Losari Kidul',
        'Losari Lor',
        'Negla',
        'Pekauman',
        'Pengabean',
        'Prapag Kidul',
        'Prapag Lor',
        'Radegan',
        'Randusari',
        'Rungkang',
    ],
    'Paguyangan' => [
        'Cilibur',
        'Cipetung',
        'Kedungoleng',
        'Kretek',
        'Pagojengan',
        'Paguyangan',
        'Pakujati',
        'Pandansari',
        'Ragatunjung',
        'Taraban',
        'Wanatirta',
        'Winduaji',
    ],
    'Salem' => [
        'Banjaran',
        'Bentar',
        'Bentarsari',
        'Capar',
        'Ciputih',
        'Citimbang',
        'Gandoang',
        'Ganggawang',
        'Gunung Jaya',
        'Gunung Larang',
        'Gunung Sugih',
        'Gunung Tajem',
        'Indrajaya',
        'Kadumanis',
        'Pabuaran',
        'Pasir Panjang',
        'Salem',
        'Tembongraja',
        'Wanoja',
        'Winduasri',
        'Windusakti',
    ],
    'Sirampog' => [
        'Batursari',
        'Benda',
        'Buniwah',
        'Dawuhan',
        'Igirklanceng',
        'Kaligiri',
        'Kaliloka',
        'Manggis',
        'Mendala',
        'Mlayang',
        'Plompong',
        'Sridadi',
        'Wanareja',
    ],
    'Songgom' => [
        'Cenang',
        'Dukuhmaja',
        'Gegerkunci',
        'Jatimakmur',
        'Jatirokeh',
        'Karangsembung',
        'Songgom',
        'Songgom Lor',
        'Wanacala',
        'Wanatawang',
    ],
    'Tanjung' => [
        'Karangreja',
        'Kedawung',
        'Kemurang Kulon',
        'Kemurang Wetan',
        'Krakahan',
        'Kubangputat',
        'Lemah Abang',
        'Luwung Gede',
        'Luwungbata',
        'Mundu',
        'Pejagan',
        'Pengaradan',
        'Sarireja',
        'Sengon',
        'Sidakaton',
        'Tanjung',
        'Tegongan',
        'Tengguli',
    ],
    'Tonjong' => [
        'Galuh Timur',
        'Kalijurang',
        'Karangjongkeng',
        'Kutamendala',
        'Kutayu',
        'Linggapura',
        'Negarayu',
        'Pepedan',
        'Purbayasa',
        'Purwodadi',
        'Rajawetan',
        'Tanggeran',
        'Tonjong',
        'Watujaya',
    ],
    'Wanasari' => [
        'Pesantunan',
        'Pebatan',
        'Dukuhwringin',
        'Dumeling',
        'Glonggong',
        'Jagalempeni',
        'Keboledan',
        'Kertabesuki',
        'Klampok',
        'Kupu',
        'Lengkong',
        'Sawojajar',
        'Siasem',
        'Sidamulya',
        'Sigentong',
        'Sisalam',
        'Siwungkuk',
        'Tanjungsari',
        'Tegalgandu',
        'Wanasari',
    ],

];
